import '../styles/globals.css';
import Head from 'next/head';
import Header from '../components/Header';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Radivoje Dundjerovic - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <Header />
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
